name = input("Enter Employee name: ")
h_worked = eval(input("Enter number of hours worked in a week: "))
H_p_rate = eval(input("Enter hourly pay rate: "))
Fed = eval(input("Enter federal tax withholding rate "))
sta_tax = eval(input("Enter state tax withholding rate: "))
print("Employee name: ",name)
print("Hourly worked: ",h_worked)
print("Pay rate : $"+str(H_p_rate))
G_pay = (H_p_rate*10)
print("Gross pay rate : $"+str(H_p_rate*10))
print("DEDUCTION: ")
print(f"Federal widthholding : {Fed*10}%:",G_pay*20/100)
print(f"State widthholding : {sta_tax*10}%:",G_pay*sta_tax)
print("Total deduction: ")
print((G_pay*20/100) + (G_pay*sta_tax))
N = G_pay - (G_pay*20/100) - (G_pay*sta_tax)
print("Net pay : ",N)
